apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-extensions
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"